{{ config(materialized='table') }}

WITH booking_dates AS (
    SELECT DISTINCT BOOKING_DATE AS DATE_DAY
    FROM {{ ref('silver_bookings') }}
    WHERE BOOKING_DATE IS NOT NULL
)

SELECT
    DATE_DAY,
    EXTRACT(YEAR FROM DATE_DAY) AS YEAR,
    EXTRACT(MONTH FROM DATE_DAY) AS MONTH,
    TO_VARCHAR(DATE_DAY, 'MON') AS MONTH_NAME,
    EXTRACT(QUARTER FROM DATE_DAY) AS QUARTER,
    DAYOFWEEK(DATE_DAY) AS DAY_OF_WEEK,
    WEEKOFYEAR(DATE_DAY) AS WEEK_OF_YEAR
FROM booking_dates
